// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-wfEdt0ez6p5_KJRWaPAjaQ64Rje0jxo',
    appId: '1:518757464681:android:8dbaf68ab3a56ca78b80f8',
    messagingSenderId: '518757464681',
    projectId: 'mentorme-2e120',
    databaseURL: 'https://mentorme-2e120-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mentorme-2e120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Xb91J3Ga1YbeKokMQYeFlaklcHs7ZeM',
    appId: '1:518757464681:ios:a148d6533dcb42918b80f8',
    messagingSenderId: '518757464681',
    projectId: 'mentorme-2e120',
    databaseURL: 'https://mentorme-2e120-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mentorme-2e120.appspot.com',
    iosBundleId: 'com.example.mentormementor',
  );
}
